// flow-typed signature: e170dcd7b5797c6c51e1489189656914
// flow-typed version: <<STUB>>/@functional-data-structure/finger-tree_v^8.0.0/flow_v0.168.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@functional-data-structure/finger-tree'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@functional-data-structure/finger-tree' {
  declare type Measure<T, M> = {
    plus(x: M, y: M): M,
    measure(x: T): M,
    zero(): M,
  }

  declare type Tree<T, M> = {
    measure(): M,
    isEmpty(): boolean,
    head(): T,
    last(): T,
    push(x: T): Tree<T, M>,
    cons(x: T): Tree<T, M>,
    init(): Tree<T, M>,
    tail(): Tree<T, M>,
    split(pred: (m: M) => boolean): [Tree<T, M>, Tree<T, M>],
    concat(t: Tree<T, M>): Tree<T, M>,
    @@iterator(): Iterator<T>,
  };

  declare function empty<T, M>(m: Measure<T, M>): Tree<T, M>;

  declare function from<T, M>(m: Measure<T, M>, it: Iterable<T>): Tree<T, M>;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@functional-data-structure/finger-tree/dist/index.modern' {
  declare module.exports: any;
}

declare module '@functional-data-structure/finger-tree/dist/index.module' {
  declare module.exports: any;
}

declare module '@functional-data-structure/finger-tree/dist/index.umd' {
  declare module.exports: any;
}

// Filename aliases
declare module '@functional-data-structure/finger-tree/dist/index.modern.js' {
  declare module.exports: $Exports<'@functional-data-structure/finger-tree/dist/index.modern'>;
}
declare module '@functional-data-structure/finger-tree/dist/index.module.js' {
  declare module.exports: $Exports<'@functional-data-structure/finger-tree/dist/index.module'>;
}
declare module '@functional-data-structure/finger-tree/dist/index.umd.js' {
  declare module.exports: $Exports<'@functional-data-structure/finger-tree/dist/index.umd'>;
}
