// flow-typed signature: d2a8abddcaea4b488de046ad59dc3214
// flow-typed version: <<STUB>>/big-integer_v^1.6.51/flow_v0.168.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'big-integer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'big-integer' {
  declare type BigInteger = {
    toJSNumber(): number,

    add(n: number | BigInteger): BigInteger,
    subtract(n: number | BigInteger): BigInteger,
    multiply(n: number | BigInteger): BigInteger,
    divide(n: number | BigInteger): BigInteger,
    mod(n: number | BigInteger): BigInteger,
    divmod(n: number | BigInteger): {
      quotient: BigInteger,
      remainder: BigInteger,
    },
    pow(n: number | BigInteger): BigInteger,

    lt(n: number | BigInteger): boolean,
    gt(n: number | BigInteger): boolean,
    leq(n: number | BigInteger): boolean,
    geq(n: number | BigInteger): boolean,
    equals(n: number | BigInteger): boolean,
    compare(n: number | BigInteger): 1 | 0 | -1,

    isEven(): boolean,
    isOdd(): boolean,
    isPositive(): boolean,
    isNegative(): boolean,

    next(): BigInteger,
    prev(): BigInteger,

    shiftLeft(n: number): BigInteger,
    shiftRight(n: number): BigInteger,
  }

  declare module.exports: {
    (n: number | string): BigInteger,
    zero: BigInteger,
    gcd: (a: number | BigInteger, b: number | BigInteger) => BigInteger,
  };
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'big-integer/BigInteger' {
  declare module.exports: any;
}

declare module 'big-integer/BigInteger.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'big-integer/BigInteger.js' {
  declare module.exports: $Exports<'big-integer/BigInteger'>;
}
declare module 'big-integer/BigInteger.min.js' {
  declare module.exports: $Exports<'big-integer/BigInteger.min'>;
}
