// flow-typed signature: 6dc72adb83dccfc0ffc297a5e4e45358
// flow-typed version: <<STUB>>/fast-check_v2.7.0/flow_v0.138.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fast-check'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fast-check' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fast-check/lib/check/arbitrary/ArrayArbitrary' {
  declare module.exports: any;
}

declare module 'fast-check/lib/check/arbitrary/AsyncSchedulerArbitrary' {
  declare module.exports: any;
}

declare module 'fast-check/lib/check/arbitrary/BigIntArbitrary' {
  declare module.exports: any;
}

declare module 'fast-check/lib/check/arbitrary/BooleanArbitrary' {
  declare module.exports: any;
}

declare module 'fast-check/lib/check/arbitrary/CharacterArbitrary' {
  declare module.exports: any;
}

declare module 'fast-check/lib/check/arbitrary/CloneArbitrary' {
  declare module.exports: any;
}

declare module 'fast-check/lib/check/arbitrary/ConstantArbitrary' {
  declare module.exports: any;
}

declare module 'fast-check/lib/check/arbitrary/ContextArbitrary' {
  declare module.exports: any;
}

declare module 'fast-check/lib/check/arbitrary/DateArbitrary' {
  declare module.exports: any;
}

declare module 'fast-check/lib/check/arbitrary/DedupArbitrary' {
  declare module.exports: any;
}

declare module 'fast-check/lib/check/arbitrary/definition/Arbitrary' {
  declare module.exports: any;
}

declare module 'fast-check/lib/check/arbitrary/definition/ArbitraryWithShrink' {
  declare module.exports: any;
}

declare module 'fast-check/lib/check/arbitrary/definition/BiasedArbitraryWrapper' {
  declare module.exports: any;
}

declare module 'fast-check/lib/check/arbitrary/definition/Shrinkable' {
  declare module.exports: any;
}

declare module 'fast-check/lib/check/arbitrary/DictionaryArbitrary' {
  declare module.exports: any;
}

declare module 'fast-check/lib/check/arbitrary/EmailArbitrary' {
  declare module.exports: any;
}

declare module 'fast-check/lib/check/arbitrary/FalsyArbitrary' {
  declare module.exports: any;
}

declare module 'fast-check/lib/check/arbitrary/FloatingPointArbitrary' {
  declare module.exports: any;
}

declare module 'fast-check/lib/check/arbitrary/FrequencyArbitrary' {
  declare module.exports: any;
}

declare module 'fast-check/lib/check/arbitrary/FunctionArbitrary' {
  declare module.exports: any;
}

declare module 'fast-check/lib/check/arbitrary/helpers/BiasNumeric' {
  declare module.exports: any;
}

declare module 'fast-check/lib/check/arbitrary/helpers/BuildCompareFilter' {
  declare module.exports: any;
}

declare module 'fast-check/lib/check/arbitrary/helpers/ShrinkNumeric' {
  declare module.exports: any;
}

declare module 'fast-check/lib/check/arbitrary/helpers/SpecificCharacterRange' {
  declare module.exports: any;
}

declare module 'fast-check/lib/check/arbitrary/helpers/TextEscaper' {
  declare module.exports: any;
}

declare module 'fast-check/lib/check/arbitrary/HostArbitrary' {
  declare module.exports: any;
}

declare module 'fast-check/lib/check/arbitrary/IntegerArbitrary' {
  declare module.exports: any;
}

declare module 'fast-check/lib/check/arbitrary/IpArbitrary' {
  declare module.exports: any;
}

declare module 'fast-check/lib/check/arbitrary/LetRecArbitrary' {
  declare module.exports: any;
}

declare module 'fast-check/lib/check/arbitrary/LoremArbitrary' {
  declare module.exports: any;
}

declare module 'fast-check/lib/check/arbitrary/MapToConstantArbitrary' {
  declare module.exports: any;
}

declare module 'fast-check/lib/check/arbitrary/MemoArbitrary' {
  declare module.exports: any;
}

declare module 'fast-check/lib/check/arbitrary/MixedCaseArbitrary' {
  declare module.exports: any;
}

declare module 'fast-check/lib/check/arbitrary/ObjectArbitrary' {
  declare module.exports: any;
}

declare module 'fast-check/lib/check/arbitrary/OneOfArbitrary' {
  declare module.exports: any;
}

declare module 'fast-check/lib/check/arbitrary/OptionArbitrary' {
  declare module.exports: any;
}

declare module 'fast-check/lib/check/arbitrary/RecordArbitrary' {
  declare module.exports: any;
}

declare module 'fast-check/lib/check/arbitrary/SetArbitrary' {
  declare module.exports: any;
}

declare module 'fast-check/lib/check/arbitrary/StreamArbitrary' {
  declare module.exports: any;
}

declare module 'fast-check/lib/check/arbitrary/StringArbitrary' {
  declare module.exports: any;
}

declare module 'fast-check/lib/check/arbitrary/SubarrayArbitrary' {
  declare module.exports: any;
}

declare module 'fast-check/lib/check/arbitrary/TupleArbitrary.generated' {
  declare module.exports: any;
}

declare module 'fast-check/lib/check/arbitrary/TupleArbitrary.generic' {
  declare module.exports: any;
}

declare module 'fast-check/lib/check/arbitrary/TupleArbitrary' {
  declare module.exports: any;
}

declare module 'fast-check/lib/check/arbitrary/UuidArbitrary' {
  declare module.exports: any;
}

declare module 'fast-check/lib/check/arbitrary/WebArbitrary' {
  declare module.exports: any;
}

declare module 'fast-check/lib/check/model/command/AsyncCommand' {
  declare module.exports: any;
}

declare module 'fast-check/lib/check/model/command/Command' {
  declare module.exports: any;
}

declare module 'fast-check/lib/check/model/command/ICommand' {
  declare module.exports: any;
}

declare module 'fast-check/lib/check/model/commands/CommandsArbitrary' {
  declare module.exports: any;
}

declare module 'fast-check/lib/check/model/commands/CommandsContraints' {
  declare module.exports: any;
}

declare module 'fast-check/lib/check/model/commands/CommandsIterable' {
  declare module.exports: any;
}

declare module 'fast-check/lib/check/model/commands/CommandWrapper' {
  declare module.exports: any;
}

declare module 'fast-check/lib/check/model/commands/ScheduledCommand' {
  declare module.exports: any;
}

declare module 'fast-check/lib/check/model/ModelRunner' {
  declare module.exports: any;
}

declare module 'fast-check/lib/check/model/ReplayPath' {
  declare module.exports: any;
}

declare module 'fast-check/lib/check/precondition/Pre' {
  declare module.exports: any;
}

declare module 'fast-check/lib/check/precondition/PreconditionFailure' {
  declare module.exports: any;
}

declare module 'fast-check/lib/check/property/AsyncProperty.generated' {
  declare module.exports: any;
}

declare module 'fast-check/lib/check/property/AsyncProperty.generic' {
  declare module.exports: any;
}

declare module 'fast-check/lib/check/property/AsyncProperty' {
  declare module.exports: any;
}

declare module 'fast-check/lib/check/property/IRawProperty' {
  declare module.exports: any;
}

declare module 'fast-check/lib/check/property/Property.generated' {
  declare module.exports: any;
}

declare module 'fast-check/lib/check/property/Property.generic' {
  declare module.exports: any;
}

declare module 'fast-check/lib/check/property/Property' {
  declare module.exports: any;
}

declare module 'fast-check/lib/check/property/SkipAfterProperty' {
  declare module.exports: any;
}

declare module 'fast-check/lib/check/property/TimeoutProperty' {
  declare module.exports: any;
}

declare module 'fast-check/lib/check/property/UnbiasedProperty' {
  declare module.exports: any;
}

declare module 'fast-check/lib/check/runner/configuration/GlobalParameters' {
  declare module.exports: any;
}

declare module 'fast-check/lib/check/runner/configuration/Parameters' {
  declare module.exports: any;
}

declare module 'fast-check/lib/check/runner/configuration/QualifiedParameters' {
  declare module.exports: any;
}

declare module 'fast-check/lib/check/runner/configuration/RandomType' {
  declare module.exports: any;
}

declare module 'fast-check/lib/check/runner/configuration/VerbosityLevel' {
  declare module.exports: any;
}

declare module 'fast-check/lib/check/runner/DecorateProperty' {
  declare module.exports: any;
}

declare module 'fast-check/lib/check/runner/reporter/ExecutionStatus' {
  declare module.exports: any;
}

declare module 'fast-check/lib/check/runner/reporter/ExecutionTree' {
  declare module.exports: any;
}

declare module 'fast-check/lib/check/runner/reporter/RunDetails' {
  declare module.exports: any;
}

declare module 'fast-check/lib/check/runner/reporter/RunExecution' {
  declare module.exports: any;
}

declare module 'fast-check/lib/check/runner/Runner' {
  declare module.exports: any;
}

declare module 'fast-check/lib/check/runner/RunnerIterator' {
  declare module.exports: any;
}

declare module 'fast-check/lib/check/runner/Sampler' {
  declare module.exports: any;
}

declare module 'fast-check/lib/check/runner/SourceValuesIterator' {
  declare module.exports: any;
}

declare module 'fast-check/lib/check/runner/Tosser' {
  declare module.exports: any;
}

declare module 'fast-check/lib/check/runner/utils/PathWalker' {
  declare module.exports: any;
}

declare module 'fast-check/lib/check/runner/utils/RunDetailsFormatter' {
  declare module.exports: any;
}

declare module 'fast-check/lib/check/symbols' {
  declare module.exports: any;
}

declare module 'fast-check/lib/esm/check/arbitrary/ArrayArbitrary' {
  declare module.exports: any;
}

declare module 'fast-check/lib/esm/check/arbitrary/AsyncSchedulerArbitrary' {
  declare module.exports: any;
}

declare module 'fast-check/lib/esm/check/arbitrary/BigIntArbitrary' {
  declare module.exports: any;
}

declare module 'fast-check/lib/esm/check/arbitrary/BooleanArbitrary' {
  declare module.exports: any;
}

declare module 'fast-check/lib/esm/check/arbitrary/CharacterArbitrary' {
  declare module.exports: any;
}

declare module 'fast-check/lib/esm/check/arbitrary/CloneArbitrary' {
  declare module.exports: any;
}

declare module 'fast-check/lib/esm/check/arbitrary/ConstantArbitrary' {
  declare module.exports: any;
}

declare module 'fast-check/lib/esm/check/arbitrary/ContextArbitrary' {
  declare module.exports: any;
}

declare module 'fast-check/lib/esm/check/arbitrary/DateArbitrary' {
  declare module.exports: any;
}

declare module 'fast-check/lib/esm/check/arbitrary/DedupArbitrary' {
  declare module.exports: any;
}

declare module 'fast-check/lib/esm/check/arbitrary/definition/Arbitrary' {
  declare module.exports: any;
}

declare module 'fast-check/lib/esm/check/arbitrary/definition/ArbitraryWithShrink' {
  declare module.exports: any;
}

declare module 'fast-check/lib/esm/check/arbitrary/definition/BiasedArbitraryWrapper' {
  declare module.exports: any;
}

declare module 'fast-check/lib/esm/check/arbitrary/definition/Shrinkable' {
  declare module.exports: any;
}

declare module 'fast-check/lib/esm/check/arbitrary/DictionaryArbitrary' {
  declare module.exports: any;
}

declare module 'fast-check/lib/esm/check/arbitrary/EmailArbitrary' {
  declare module.exports: any;
}

declare module 'fast-check/lib/esm/check/arbitrary/FalsyArbitrary' {
  declare module.exports: any;
}

declare module 'fast-check/lib/esm/check/arbitrary/FloatingPointArbitrary' {
  declare module.exports: any;
}

declare module 'fast-check/lib/esm/check/arbitrary/FrequencyArbitrary' {
  declare module.exports: any;
}

declare module 'fast-check/lib/esm/check/arbitrary/FunctionArbitrary' {
  declare module.exports: any;
}

declare module 'fast-check/lib/esm/check/arbitrary/helpers/BiasNumeric' {
  declare module.exports: any;
}

declare module 'fast-check/lib/esm/check/arbitrary/helpers/BuildCompareFilter' {
  declare module.exports: any;
}

declare module 'fast-check/lib/esm/check/arbitrary/helpers/ShrinkNumeric' {
  declare module.exports: any;
}

declare module 'fast-check/lib/esm/check/arbitrary/helpers/SpecificCharacterRange' {
  declare module.exports: any;
}

declare module 'fast-check/lib/esm/check/arbitrary/helpers/TextEscaper' {
  declare module.exports: any;
}

declare module 'fast-check/lib/esm/check/arbitrary/HostArbitrary' {
  declare module.exports: any;
}

declare module 'fast-check/lib/esm/check/arbitrary/IntegerArbitrary' {
  declare module.exports: any;
}

declare module 'fast-check/lib/esm/check/arbitrary/IpArbitrary' {
  declare module.exports: any;
}

declare module 'fast-check/lib/esm/check/arbitrary/LetRecArbitrary' {
  declare module.exports: any;
}

declare module 'fast-check/lib/esm/check/arbitrary/LoremArbitrary' {
  declare module.exports: any;
}

declare module 'fast-check/lib/esm/check/arbitrary/MapToConstantArbitrary' {
  declare module.exports: any;
}

declare module 'fast-check/lib/esm/check/arbitrary/MemoArbitrary' {
  declare module.exports: any;
}

declare module 'fast-check/lib/esm/check/arbitrary/MixedCaseArbitrary' {
  declare module.exports: any;
}

declare module 'fast-check/lib/esm/check/arbitrary/ObjectArbitrary' {
  declare module.exports: any;
}

declare module 'fast-check/lib/esm/check/arbitrary/OneOfArbitrary' {
  declare module.exports: any;
}

declare module 'fast-check/lib/esm/check/arbitrary/OptionArbitrary' {
  declare module.exports: any;
}

declare module 'fast-check/lib/esm/check/arbitrary/RecordArbitrary' {
  declare module.exports: any;
}

declare module 'fast-check/lib/esm/check/arbitrary/SetArbitrary' {
  declare module.exports: any;
}

declare module 'fast-check/lib/esm/check/arbitrary/StreamArbitrary' {
  declare module.exports: any;
}

declare module 'fast-check/lib/esm/check/arbitrary/StringArbitrary' {
  declare module.exports: any;
}

declare module 'fast-check/lib/esm/check/arbitrary/SubarrayArbitrary' {
  declare module.exports: any;
}

declare module 'fast-check/lib/esm/check/arbitrary/TupleArbitrary.generated' {
  declare module.exports: any;
}

declare module 'fast-check/lib/esm/check/arbitrary/TupleArbitrary.generic' {
  declare module.exports: any;
}

declare module 'fast-check/lib/esm/check/arbitrary/TupleArbitrary' {
  declare module.exports: any;
}

declare module 'fast-check/lib/esm/check/arbitrary/UuidArbitrary' {
  declare module.exports: any;
}

declare module 'fast-check/lib/esm/check/arbitrary/WebArbitrary' {
  declare module.exports: any;
}

declare module 'fast-check/lib/esm/check/model/command/AsyncCommand' {
  declare module.exports: any;
}

declare module 'fast-check/lib/esm/check/model/command/Command' {
  declare module.exports: any;
}

declare module 'fast-check/lib/esm/check/model/command/ICommand' {
  declare module.exports: any;
}

declare module 'fast-check/lib/esm/check/model/commands/CommandsArbitrary' {
  declare module.exports: any;
}

declare module 'fast-check/lib/esm/check/model/commands/CommandsContraints' {
  declare module.exports: any;
}

declare module 'fast-check/lib/esm/check/model/commands/CommandsIterable' {
  declare module.exports: any;
}

declare module 'fast-check/lib/esm/check/model/commands/CommandWrapper' {
  declare module.exports: any;
}

declare module 'fast-check/lib/esm/check/model/commands/ScheduledCommand' {
  declare module.exports: any;
}

declare module 'fast-check/lib/esm/check/model/ModelRunner' {
  declare module.exports: any;
}

declare module 'fast-check/lib/esm/check/model/ReplayPath' {
  declare module.exports: any;
}

declare module 'fast-check/lib/esm/check/precondition/Pre' {
  declare module.exports: any;
}

declare module 'fast-check/lib/esm/check/precondition/PreconditionFailure' {
  declare module.exports: any;
}

declare module 'fast-check/lib/esm/check/property/AsyncProperty.generated' {
  declare module.exports: any;
}

declare module 'fast-check/lib/esm/check/property/AsyncProperty.generic' {
  declare module.exports: any;
}

declare module 'fast-check/lib/esm/check/property/AsyncProperty' {
  declare module.exports: any;
}

declare module 'fast-check/lib/esm/check/property/IRawProperty' {
  declare module.exports: any;
}

declare module 'fast-check/lib/esm/check/property/Property.generated' {
  declare module.exports: any;
}

declare module 'fast-check/lib/esm/check/property/Property.generic' {
  declare module.exports: any;
}

declare module 'fast-check/lib/esm/check/property/Property' {
  declare module.exports: any;
}

declare module 'fast-check/lib/esm/check/property/SkipAfterProperty' {
  declare module.exports: any;
}

declare module 'fast-check/lib/esm/check/property/TimeoutProperty' {
  declare module.exports: any;
}

declare module 'fast-check/lib/esm/check/property/UnbiasedProperty' {
  declare module.exports: any;
}

declare module 'fast-check/lib/esm/check/runner/configuration/GlobalParameters' {
  declare module.exports: any;
}

declare module 'fast-check/lib/esm/check/runner/configuration/Parameters' {
  declare module.exports: any;
}

declare module 'fast-check/lib/esm/check/runner/configuration/QualifiedParameters' {
  declare module.exports: any;
}

declare module 'fast-check/lib/esm/check/runner/configuration/RandomType' {
  declare module.exports: any;
}

declare module 'fast-check/lib/esm/check/runner/configuration/VerbosityLevel' {
  declare module.exports: any;
}

declare module 'fast-check/lib/esm/check/runner/DecorateProperty' {
  declare module.exports: any;
}

declare module 'fast-check/lib/esm/check/runner/reporter/ExecutionStatus' {
  declare module.exports: any;
}

declare module 'fast-check/lib/esm/check/runner/reporter/ExecutionTree' {
  declare module.exports: any;
}

declare module 'fast-check/lib/esm/check/runner/reporter/RunDetails' {
  declare module.exports: any;
}

declare module 'fast-check/lib/esm/check/runner/reporter/RunExecution' {
  declare module.exports: any;
}

declare module 'fast-check/lib/esm/check/runner/Runner' {
  declare module.exports: any;
}

declare module 'fast-check/lib/esm/check/runner/RunnerIterator' {
  declare module.exports: any;
}

declare module 'fast-check/lib/esm/check/runner/Sampler' {
  declare module.exports: any;
}

declare module 'fast-check/lib/esm/check/runner/SourceValuesIterator' {
  declare module.exports: any;
}

declare module 'fast-check/lib/esm/check/runner/Tosser' {
  declare module.exports: any;
}

declare module 'fast-check/lib/esm/check/runner/utils/PathWalker' {
  declare module.exports: any;
}

declare module 'fast-check/lib/esm/check/runner/utils/RunDetailsFormatter' {
  declare module.exports: any;
}

declare module 'fast-check/lib/esm/check/symbols' {
  declare module.exports: any;
}

declare module 'fast-check/lib/esm/fast-check-default' {
  declare module.exports: any;
}

declare module 'fast-check/lib/esm/fast-check' {
  declare module.exports: any;
}

declare module 'fast-check/lib/esm/random/generator/Random' {
  declare module.exports: any;
}

declare module 'fast-check/lib/esm/stream/LazyIterableIterator' {
  declare module.exports: any;
}

declare module 'fast-check/lib/esm/stream/Stream' {
  declare module.exports: any;
}

declare module 'fast-check/lib/esm/stream/StreamHelpers' {
  declare module.exports: any;
}

declare module 'fast-check/lib/esm/utils/globalThis' {
  declare module.exports: any;
}

declare module 'fast-check/lib/esm/utils/hash' {
  declare module.exports: any;
}

declare module 'fast-check/lib/esm/utils/stringify' {
  declare module.exports: any;
}

declare module 'fast-check/lib/fast-check-default' {
  declare module.exports: any;
}

declare module 'fast-check/lib/fast-check' {
  declare module.exports: any;
}

declare module 'fast-check/lib/random/generator/Random' {
  declare module.exports: any;
}

declare module 'fast-check/lib/stream/LazyIterableIterator' {
  declare module.exports: any;
}

declare module 'fast-check/lib/stream/Stream' {
  declare module.exports: any;
}

declare module 'fast-check/lib/stream/StreamHelpers' {
  declare module.exports: any;
}

declare module 'fast-check/lib/utils/globalThis' {
  declare module.exports: any;
}

declare module 'fast-check/lib/utils/hash' {
  declare module.exports: any;
}

declare module 'fast-check/lib/utils/stringify' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fast-check/lib/check/arbitrary/ArrayArbitrary.js' {
  declare module.exports: $Exports<'fast-check/lib/check/arbitrary/ArrayArbitrary'>;
}
declare module 'fast-check/lib/check/arbitrary/AsyncSchedulerArbitrary.js' {
  declare module.exports: $Exports<'fast-check/lib/check/arbitrary/AsyncSchedulerArbitrary'>;
}
declare module 'fast-check/lib/check/arbitrary/BigIntArbitrary.js' {
  declare module.exports: $Exports<'fast-check/lib/check/arbitrary/BigIntArbitrary'>;
}
declare module 'fast-check/lib/check/arbitrary/BooleanArbitrary.js' {
  declare module.exports: $Exports<'fast-check/lib/check/arbitrary/BooleanArbitrary'>;
}
declare module 'fast-check/lib/check/arbitrary/CharacterArbitrary.js' {
  declare module.exports: $Exports<'fast-check/lib/check/arbitrary/CharacterArbitrary'>;
}
declare module 'fast-check/lib/check/arbitrary/CloneArbitrary.js' {
  declare module.exports: $Exports<'fast-check/lib/check/arbitrary/CloneArbitrary'>;
}
declare module 'fast-check/lib/check/arbitrary/ConstantArbitrary.js' {
  declare module.exports: $Exports<'fast-check/lib/check/arbitrary/ConstantArbitrary'>;
}
declare module 'fast-check/lib/check/arbitrary/ContextArbitrary.js' {
  declare module.exports: $Exports<'fast-check/lib/check/arbitrary/ContextArbitrary'>;
}
declare module 'fast-check/lib/check/arbitrary/DateArbitrary.js' {
  declare module.exports: $Exports<'fast-check/lib/check/arbitrary/DateArbitrary'>;
}
declare module 'fast-check/lib/check/arbitrary/DedupArbitrary.js' {
  declare module.exports: $Exports<'fast-check/lib/check/arbitrary/DedupArbitrary'>;
}
declare module 'fast-check/lib/check/arbitrary/definition/Arbitrary.js' {
  declare module.exports: $Exports<'fast-check/lib/check/arbitrary/definition/Arbitrary'>;
}
declare module 'fast-check/lib/check/arbitrary/definition/ArbitraryWithShrink.js' {
  declare module.exports: $Exports<'fast-check/lib/check/arbitrary/definition/ArbitraryWithShrink'>;
}
declare module 'fast-check/lib/check/arbitrary/definition/BiasedArbitraryWrapper.js' {
  declare module.exports: $Exports<'fast-check/lib/check/arbitrary/definition/BiasedArbitraryWrapper'>;
}
declare module 'fast-check/lib/check/arbitrary/definition/Shrinkable.js' {
  declare module.exports: $Exports<'fast-check/lib/check/arbitrary/definition/Shrinkable'>;
}
declare module 'fast-check/lib/check/arbitrary/DictionaryArbitrary.js' {
  declare module.exports: $Exports<'fast-check/lib/check/arbitrary/DictionaryArbitrary'>;
}
declare module 'fast-check/lib/check/arbitrary/EmailArbitrary.js' {
  declare module.exports: $Exports<'fast-check/lib/check/arbitrary/EmailArbitrary'>;
}
declare module 'fast-check/lib/check/arbitrary/FalsyArbitrary.js' {
  declare module.exports: $Exports<'fast-check/lib/check/arbitrary/FalsyArbitrary'>;
}
declare module 'fast-check/lib/check/arbitrary/FloatingPointArbitrary.js' {
  declare module.exports: $Exports<'fast-check/lib/check/arbitrary/FloatingPointArbitrary'>;
}
declare module 'fast-check/lib/check/arbitrary/FrequencyArbitrary.js' {
  declare module.exports: $Exports<'fast-check/lib/check/arbitrary/FrequencyArbitrary'>;
}
declare module 'fast-check/lib/check/arbitrary/FunctionArbitrary.js' {
  declare module.exports: $Exports<'fast-check/lib/check/arbitrary/FunctionArbitrary'>;
}
declare module 'fast-check/lib/check/arbitrary/helpers/BiasNumeric.js' {
  declare module.exports: $Exports<'fast-check/lib/check/arbitrary/helpers/BiasNumeric'>;
}
declare module 'fast-check/lib/check/arbitrary/helpers/BuildCompareFilter.js' {
  declare module.exports: $Exports<'fast-check/lib/check/arbitrary/helpers/BuildCompareFilter'>;
}
declare module 'fast-check/lib/check/arbitrary/helpers/ShrinkNumeric.js' {
  declare module.exports: $Exports<'fast-check/lib/check/arbitrary/helpers/ShrinkNumeric'>;
}
declare module 'fast-check/lib/check/arbitrary/helpers/SpecificCharacterRange.js' {
  declare module.exports: $Exports<'fast-check/lib/check/arbitrary/helpers/SpecificCharacterRange'>;
}
declare module 'fast-check/lib/check/arbitrary/helpers/TextEscaper.js' {
  declare module.exports: $Exports<'fast-check/lib/check/arbitrary/helpers/TextEscaper'>;
}
declare module 'fast-check/lib/check/arbitrary/HostArbitrary.js' {
  declare module.exports: $Exports<'fast-check/lib/check/arbitrary/HostArbitrary'>;
}
declare module 'fast-check/lib/check/arbitrary/IntegerArbitrary.js' {
  declare module.exports: $Exports<'fast-check/lib/check/arbitrary/IntegerArbitrary'>;
}
declare module 'fast-check/lib/check/arbitrary/IpArbitrary.js' {
  declare module.exports: $Exports<'fast-check/lib/check/arbitrary/IpArbitrary'>;
}
declare module 'fast-check/lib/check/arbitrary/LetRecArbitrary.js' {
  declare module.exports: $Exports<'fast-check/lib/check/arbitrary/LetRecArbitrary'>;
}
declare module 'fast-check/lib/check/arbitrary/LoremArbitrary.js' {
  declare module.exports: $Exports<'fast-check/lib/check/arbitrary/LoremArbitrary'>;
}
declare module 'fast-check/lib/check/arbitrary/MapToConstantArbitrary.js' {
  declare module.exports: $Exports<'fast-check/lib/check/arbitrary/MapToConstantArbitrary'>;
}
declare module 'fast-check/lib/check/arbitrary/MemoArbitrary.js' {
  declare module.exports: $Exports<'fast-check/lib/check/arbitrary/MemoArbitrary'>;
}
declare module 'fast-check/lib/check/arbitrary/MixedCaseArbitrary.js' {
  declare module.exports: $Exports<'fast-check/lib/check/arbitrary/MixedCaseArbitrary'>;
}
declare module 'fast-check/lib/check/arbitrary/ObjectArbitrary.js' {
  declare module.exports: $Exports<'fast-check/lib/check/arbitrary/ObjectArbitrary'>;
}
declare module 'fast-check/lib/check/arbitrary/OneOfArbitrary.js' {
  declare module.exports: $Exports<'fast-check/lib/check/arbitrary/OneOfArbitrary'>;
}
declare module 'fast-check/lib/check/arbitrary/OptionArbitrary.js' {
  declare module.exports: $Exports<'fast-check/lib/check/arbitrary/OptionArbitrary'>;
}
declare module 'fast-check/lib/check/arbitrary/RecordArbitrary.js' {
  declare module.exports: $Exports<'fast-check/lib/check/arbitrary/RecordArbitrary'>;
}
declare module 'fast-check/lib/check/arbitrary/SetArbitrary.js' {
  declare module.exports: $Exports<'fast-check/lib/check/arbitrary/SetArbitrary'>;
}
declare module 'fast-check/lib/check/arbitrary/StreamArbitrary.js' {
  declare module.exports: $Exports<'fast-check/lib/check/arbitrary/StreamArbitrary'>;
}
declare module 'fast-check/lib/check/arbitrary/StringArbitrary.js' {
  declare module.exports: $Exports<'fast-check/lib/check/arbitrary/StringArbitrary'>;
}
declare module 'fast-check/lib/check/arbitrary/SubarrayArbitrary.js' {
  declare module.exports: $Exports<'fast-check/lib/check/arbitrary/SubarrayArbitrary'>;
}
declare module 'fast-check/lib/check/arbitrary/TupleArbitrary.generated.js' {
  declare module.exports: $Exports<'fast-check/lib/check/arbitrary/TupleArbitrary.generated'>;
}
declare module 'fast-check/lib/check/arbitrary/TupleArbitrary.generic.js' {
  declare module.exports: $Exports<'fast-check/lib/check/arbitrary/TupleArbitrary.generic'>;
}
declare module 'fast-check/lib/check/arbitrary/TupleArbitrary.js' {
  declare module.exports: $Exports<'fast-check/lib/check/arbitrary/TupleArbitrary'>;
}
declare module 'fast-check/lib/check/arbitrary/UuidArbitrary.js' {
  declare module.exports: $Exports<'fast-check/lib/check/arbitrary/UuidArbitrary'>;
}
declare module 'fast-check/lib/check/arbitrary/WebArbitrary.js' {
  declare module.exports: $Exports<'fast-check/lib/check/arbitrary/WebArbitrary'>;
}
declare module 'fast-check/lib/check/model/command/AsyncCommand.js' {
  declare module.exports: $Exports<'fast-check/lib/check/model/command/AsyncCommand'>;
}
declare module 'fast-check/lib/check/model/command/Command.js' {
  declare module.exports: $Exports<'fast-check/lib/check/model/command/Command'>;
}
declare module 'fast-check/lib/check/model/command/ICommand.js' {
  declare module.exports: $Exports<'fast-check/lib/check/model/command/ICommand'>;
}
declare module 'fast-check/lib/check/model/commands/CommandsArbitrary.js' {
  declare module.exports: $Exports<'fast-check/lib/check/model/commands/CommandsArbitrary'>;
}
declare module 'fast-check/lib/check/model/commands/CommandsContraints.js' {
  declare module.exports: $Exports<'fast-check/lib/check/model/commands/CommandsContraints'>;
}
declare module 'fast-check/lib/check/model/commands/CommandsIterable.js' {
  declare module.exports: $Exports<'fast-check/lib/check/model/commands/CommandsIterable'>;
}
declare module 'fast-check/lib/check/model/commands/CommandWrapper.js' {
  declare module.exports: $Exports<'fast-check/lib/check/model/commands/CommandWrapper'>;
}
declare module 'fast-check/lib/check/model/commands/ScheduledCommand.js' {
  declare module.exports: $Exports<'fast-check/lib/check/model/commands/ScheduledCommand'>;
}
declare module 'fast-check/lib/check/model/ModelRunner.js' {
  declare module.exports: $Exports<'fast-check/lib/check/model/ModelRunner'>;
}
declare module 'fast-check/lib/check/model/ReplayPath.js' {
  declare module.exports: $Exports<'fast-check/lib/check/model/ReplayPath'>;
}
declare module 'fast-check/lib/check/precondition/Pre.js' {
  declare module.exports: $Exports<'fast-check/lib/check/precondition/Pre'>;
}
declare module 'fast-check/lib/check/precondition/PreconditionFailure.js' {
  declare module.exports: $Exports<'fast-check/lib/check/precondition/PreconditionFailure'>;
}
declare module 'fast-check/lib/check/property/AsyncProperty.generated.js' {
  declare module.exports: $Exports<'fast-check/lib/check/property/AsyncProperty.generated'>;
}
declare module 'fast-check/lib/check/property/AsyncProperty.generic.js' {
  declare module.exports: $Exports<'fast-check/lib/check/property/AsyncProperty.generic'>;
}
declare module 'fast-check/lib/check/property/AsyncProperty.js' {
  declare module.exports: $Exports<'fast-check/lib/check/property/AsyncProperty'>;
}
declare module 'fast-check/lib/check/property/IRawProperty.js' {
  declare module.exports: $Exports<'fast-check/lib/check/property/IRawProperty'>;
}
declare module 'fast-check/lib/check/property/Property.generated.js' {
  declare module.exports: $Exports<'fast-check/lib/check/property/Property.generated'>;
}
declare module 'fast-check/lib/check/property/Property.generic.js' {
  declare module.exports: $Exports<'fast-check/lib/check/property/Property.generic'>;
}
declare module 'fast-check/lib/check/property/Property.js' {
  declare module.exports: $Exports<'fast-check/lib/check/property/Property'>;
}
declare module 'fast-check/lib/check/property/SkipAfterProperty.js' {
  declare module.exports: $Exports<'fast-check/lib/check/property/SkipAfterProperty'>;
}
declare module 'fast-check/lib/check/property/TimeoutProperty.js' {
  declare module.exports: $Exports<'fast-check/lib/check/property/TimeoutProperty'>;
}
declare module 'fast-check/lib/check/property/UnbiasedProperty.js' {
  declare module.exports: $Exports<'fast-check/lib/check/property/UnbiasedProperty'>;
}
declare module 'fast-check/lib/check/runner/configuration/GlobalParameters.js' {
  declare module.exports: $Exports<'fast-check/lib/check/runner/configuration/GlobalParameters'>;
}
declare module 'fast-check/lib/check/runner/configuration/Parameters.js' {
  declare module.exports: $Exports<'fast-check/lib/check/runner/configuration/Parameters'>;
}
declare module 'fast-check/lib/check/runner/configuration/QualifiedParameters.js' {
  declare module.exports: $Exports<'fast-check/lib/check/runner/configuration/QualifiedParameters'>;
}
declare module 'fast-check/lib/check/runner/configuration/RandomType.js' {
  declare module.exports: $Exports<'fast-check/lib/check/runner/configuration/RandomType'>;
}
declare module 'fast-check/lib/check/runner/configuration/VerbosityLevel.js' {
  declare module.exports: $Exports<'fast-check/lib/check/runner/configuration/VerbosityLevel'>;
}
declare module 'fast-check/lib/check/runner/DecorateProperty.js' {
  declare module.exports: $Exports<'fast-check/lib/check/runner/DecorateProperty'>;
}
declare module 'fast-check/lib/check/runner/reporter/ExecutionStatus.js' {
  declare module.exports: $Exports<'fast-check/lib/check/runner/reporter/ExecutionStatus'>;
}
declare module 'fast-check/lib/check/runner/reporter/ExecutionTree.js' {
  declare module.exports: $Exports<'fast-check/lib/check/runner/reporter/ExecutionTree'>;
}
declare module 'fast-check/lib/check/runner/reporter/RunDetails.js' {
  declare module.exports: $Exports<'fast-check/lib/check/runner/reporter/RunDetails'>;
}
declare module 'fast-check/lib/check/runner/reporter/RunExecution.js' {
  declare module.exports: $Exports<'fast-check/lib/check/runner/reporter/RunExecution'>;
}
declare module 'fast-check/lib/check/runner/Runner.js' {
  declare module.exports: $Exports<'fast-check/lib/check/runner/Runner'>;
}
declare module 'fast-check/lib/check/runner/RunnerIterator.js' {
  declare module.exports: $Exports<'fast-check/lib/check/runner/RunnerIterator'>;
}
declare module 'fast-check/lib/check/runner/Sampler.js' {
  declare module.exports: $Exports<'fast-check/lib/check/runner/Sampler'>;
}
declare module 'fast-check/lib/check/runner/SourceValuesIterator.js' {
  declare module.exports: $Exports<'fast-check/lib/check/runner/SourceValuesIterator'>;
}
declare module 'fast-check/lib/check/runner/Tosser.js' {
  declare module.exports: $Exports<'fast-check/lib/check/runner/Tosser'>;
}
declare module 'fast-check/lib/check/runner/utils/PathWalker.js' {
  declare module.exports: $Exports<'fast-check/lib/check/runner/utils/PathWalker'>;
}
declare module 'fast-check/lib/check/runner/utils/RunDetailsFormatter.js' {
  declare module.exports: $Exports<'fast-check/lib/check/runner/utils/RunDetailsFormatter'>;
}
declare module 'fast-check/lib/check/symbols.js' {
  declare module.exports: $Exports<'fast-check/lib/check/symbols'>;
}
declare module 'fast-check/lib/esm/check/arbitrary/ArrayArbitrary.js' {
  declare module.exports: $Exports<'fast-check/lib/esm/check/arbitrary/ArrayArbitrary'>;
}
declare module 'fast-check/lib/esm/check/arbitrary/AsyncSchedulerArbitrary.js' {
  declare module.exports: $Exports<'fast-check/lib/esm/check/arbitrary/AsyncSchedulerArbitrary'>;
}
declare module 'fast-check/lib/esm/check/arbitrary/BigIntArbitrary.js' {
  declare module.exports: $Exports<'fast-check/lib/esm/check/arbitrary/BigIntArbitrary'>;
}
declare module 'fast-check/lib/esm/check/arbitrary/BooleanArbitrary.js' {
  declare module.exports: $Exports<'fast-check/lib/esm/check/arbitrary/BooleanArbitrary'>;
}
declare module 'fast-check/lib/esm/check/arbitrary/CharacterArbitrary.js' {
  declare module.exports: $Exports<'fast-check/lib/esm/check/arbitrary/CharacterArbitrary'>;
}
declare module 'fast-check/lib/esm/check/arbitrary/CloneArbitrary.js' {
  declare module.exports: $Exports<'fast-check/lib/esm/check/arbitrary/CloneArbitrary'>;
}
declare module 'fast-check/lib/esm/check/arbitrary/ConstantArbitrary.js' {
  declare module.exports: $Exports<'fast-check/lib/esm/check/arbitrary/ConstantArbitrary'>;
}
declare module 'fast-check/lib/esm/check/arbitrary/ContextArbitrary.js' {
  declare module.exports: $Exports<'fast-check/lib/esm/check/arbitrary/ContextArbitrary'>;
}
declare module 'fast-check/lib/esm/check/arbitrary/DateArbitrary.js' {
  declare module.exports: $Exports<'fast-check/lib/esm/check/arbitrary/DateArbitrary'>;
}
declare module 'fast-check/lib/esm/check/arbitrary/DedupArbitrary.js' {
  declare module.exports: $Exports<'fast-check/lib/esm/check/arbitrary/DedupArbitrary'>;
}
declare module 'fast-check/lib/esm/check/arbitrary/definition/Arbitrary.js' {
  declare module.exports: $Exports<'fast-check/lib/esm/check/arbitrary/definition/Arbitrary'>;
}
declare module 'fast-check/lib/esm/check/arbitrary/definition/ArbitraryWithShrink.js' {
  declare module.exports: $Exports<'fast-check/lib/esm/check/arbitrary/definition/ArbitraryWithShrink'>;
}
declare module 'fast-check/lib/esm/check/arbitrary/definition/BiasedArbitraryWrapper.js' {
  declare module.exports: $Exports<'fast-check/lib/esm/check/arbitrary/definition/BiasedArbitraryWrapper'>;
}
declare module 'fast-check/lib/esm/check/arbitrary/definition/Shrinkable.js' {
  declare module.exports: $Exports<'fast-check/lib/esm/check/arbitrary/definition/Shrinkable'>;
}
declare module 'fast-check/lib/esm/check/arbitrary/DictionaryArbitrary.js' {
  declare module.exports: $Exports<'fast-check/lib/esm/check/arbitrary/DictionaryArbitrary'>;
}
declare module 'fast-check/lib/esm/check/arbitrary/EmailArbitrary.js' {
  declare module.exports: $Exports<'fast-check/lib/esm/check/arbitrary/EmailArbitrary'>;
}
declare module 'fast-check/lib/esm/check/arbitrary/FalsyArbitrary.js' {
  declare module.exports: $Exports<'fast-check/lib/esm/check/arbitrary/FalsyArbitrary'>;
}
declare module 'fast-check/lib/esm/check/arbitrary/FloatingPointArbitrary.js' {
  declare module.exports: $Exports<'fast-check/lib/esm/check/arbitrary/FloatingPointArbitrary'>;
}
declare module 'fast-check/lib/esm/check/arbitrary/FrequencyArbitrary.js' {
  declare module.exports: $Exports<'fast-check/lib/esm/check/arbitrary/FrequencyArbitrary'>;
}
declare module 'fast-check/lib/esm/check/arbitrary/FunctionArbitrary.js' {
  declare module.exports: $Exports<'fast-check/lib/esm/check/arbitrary/FunctionArbitrary'>;
}
declare module 'fast-check/lib/esm/check/arbitrary/helpers/BiasNumeric.js' {
  declare module.exports: $Exports<'fast-check/lib/esm/check/arbitrary/helpers/BiasNumeric'>;
}
declare module 'fast-check/lib/esm/check/arbitrary/helpers/BuildCompareFilter.js' {
  declare module.exports: $Exports<'fast-check/lib/esm/check/arbitrary/helpers/BuildCompareFilter'>;
}
declare module 'fast-check/lib/esm/check/arbitrary/helpers/ShrinkNumeric.js' {
  declare module.exports: $Exports<'fast-check/lib/esm/check/arbitrary/helpers/ShrinkNumeric'>;
}
declare module 'fast-check/lib/esm/check/arbitrary/helpers/SpecificCharacterRange.js' {
  declare module.exports: $Exports<'fast-check/lib/esm/check/arbitrary/helpers/SpecificCharacterRange'>;
}
declare module 'fast-check/lib/esm/check/arbitrary/helpers/TextEscaper.js' {
  declare module.exports: $Exports<'fast-check/lib/esm/check/arbitrary/helpers/TextEscaper'>;
}
declare module 'fast-check/lib/esm/check/arbitrary/HostArbitrary.js' {
  declare module.exports: $Exports<'fast-check/lib/esm/check/arbitrary/HostArbitrary'>;
}
declare module 'fast-check/lib/esm/check/arbitrary/IntegerArbitrary.js' {
  declare module.exports: $Exports<'fast-check/lib/esm/check/arbitrary/IntegerArbitrary'>;
}
declare module 'fast-check/lib/esm/check/arbitrary/IpArbitrary.js' {
  declare module.exports: $Exports<'fast-check/lib/esm/check/arbitrary/IpArbitrary'>;
}
declare module 'fast-check/lib/esm/check/arbitrary/LetRecArbitrary.js' {
  declare module.exports: $Exports<'fast-check/lib/esm/check/arbitrary/LetRecArbitrary'>;
}
declare module 'fast-check/lib/esm/check/arbitrary/LoremArbitrary.js' {
  declare module.exports: $Exports<'fast-check/lib/esm/check/arbitrary/LoremArbitrary'>;
}
declare module 'fast-check/lib/esm/check/arbitrary/MapToConstantArbitrary.js' {
  declare module.exports: $Exports<'fast-check/lib/esm/check/arbitrary/MapToConstantArbitrary'>;
}
declare module 'fast-check/lib/esm/check/arbitrary/MemoArbitrary.js' {
  declare module.exports: $Exports<'fast-check/lib/esm/check/arbitrary/MemoArbitrary'>;
}
declare module 'fast-check/lib/esm/check/arbitrary/MixedCaseArbitrary.js' {
  declare module.exports: $Exports<'fast-check/lib/esm/check/arbitrary/MixedCaseArbitrary'>;
}
declare module 'fast-check/lib/esm/check/arbitrary/ObjectArbitrary.js' {
  declare module.exports: $Exports<'fast-check/lib/esm/check/arbitrary/ObjectArbitrary'>;
}
declare module 'fast-check/lib/esm/check/arbitrary/OneOfArbitrary.js' {
  declare module.exports: $Exports<'fast-check/lib/esm/check/arbitrary/OneOfArbitrary'>;
}
declare module 'fast-check/lib/esm/check/arbitrary/OptionArbitrary.js' {
  declare module.exports: $Exports<'fast-check/lib/esm/check/arbitrary/OptionArbitrary'>;
}
declare module 'fast-check/lib/esm/check/arbitrary/RecordArbitrary.js' {
  declare module.exports: $Exports<'fast-check/lib/esm/check/arbitrary/RecordArbitrary'>;
}
declare module 'fast-check/lib/esm/check/arbitrary/SetArbitrary.js' {
  declare module.exports: $Exports<'fast-check/lib/esm/check/arbitrary/SetArbitrary'>;
}
declare module 'fast-check/lib/esm/check/arbitrary/StreamArbitrary.js' {
  declare module.exports: $Exports<'fast-check/lib/esm/check/arbitrary/StreamArbitrary'>;
}
declare module 'fast-check/lib/esm/check/arbitrary/StringArbitrary.js' {
  declare module.exports: $Exports<'fast-check/lib/esm/check/arbitrary/StringArbitrary'>;
}
declare module 'fast-check/lib/esm/check/arbitrary/SubarrayArbitrary.js' {
  declare module.exports: $Exports<'fast-check/lib/esm/check/arbitrary/SubarrayArbitrary'>;
}
declare module 'fast-check/lib/esm/check/arbitrary/TupleArbitrary.generated.js' {
  declare module.exports: $Exports<'fast-check/lib/esm/check/arbitrary/TupleArbitrary.generated'>;
}
declare module 'fast-check/lib/esm/check/arbitrary/TupleArbitrary.generic.js' {
  declare module.exports: $Exports<'fast-check/lib/esm/check/arbitrary/TupleArbitrary.generic'>;
}
declare module 'fast-check/lib/esm/check/arbitrary/TupleArbitrary.js' {
  declare module.exports: $Exports<'fast-check/lib/esm/check/arbitrary/TupleArbitrary'>;
}
declare module 'fast-check/lib/esm/check/arbitrary/UuidArbitrary.js' {
  declare module.exports: $Exports<'fast-check/lib/esm/check/arbitrary/UuidArbitrary'>;
}
declare module 'fast-check/lib/esm/check/arbitrary/WebArbitrary.js' {
  declare module.exports: $Exports<'fast-check/lib/esm/check/arbitrary/WebArbitrary'>;
}
declare module 'fast-check/lib/esm/check/model/command/AsyncCommand.js' {
  declare module.exports: $Exports<'fast-check/lib/esm/check/model/command/AsyncCommand'>;
}
declare module 'fast-check/lib/esm/check/model/command/Command.js' {
  declare module.exports: $Exports<'fast-check/lib/esm/check/model/command/Command'>;
}
declare module 'fast-check/lib/esm/check/model/command/ICommand.js' {
  declare module.exports: $Exports<'fast-check/lib/esm/check/model/command/ICommand'>;
}
declare module 'fast-check/lib/esm/check/model/commands/CommandsArbitrary.js' {
  declare module.exports: $Exports<'fast-check/lib/esm/check/model/commands/CommandsArbitrary'>;
}
declare module 'fast-check/lib/esm/check/model/commands/CommandsContraints.js' {
  declare module.exports: $Exports<'fast-check/lib/esm/check/model/commands/CommandsContraints'>;
}
declare module 'fast-check/lib/esm/check/model/commands/CommandsIterable.js' {
  declare module.exports: $Exports<'fast-check/lib/esm/check/model/commands/CommandsIterable'>;
}
declare module 'fast-check/lib/esm/check/model/commands/CommandWrapper.js' {
  declare module.exports: $Exports<'fast-check/lib/esm/check/model/commands/CommandWrapper'>;
}
declare module 'fast-check/lib/esm/check/model/commands/ScheduledCommand.js' {
  declare module.exports: $Exports<'fast-check/lib/esm/check/model/commands/ScheduledCommand'>;
}
declare module 'fast-check/lib/esm/check/model/ModelRunner.js' {
  declare module.exports: $Exports<'fast-check/lib/esm/check/model/ModelRunner'>;
}
declare module 'fast-check/lib/esm/check/model/ReplayPath.js' {
  declare module.exports: $Exports<'fast-check/lib/esm/check/model/ReplayPath'>;
}
declare module 'fast-check/lib/esm/check/precondition/Pre.js' {
  declare module.exports: $Exports<'fast-check/lib/esm/check/precondition/Pre'>;
}
declare module 'fast-check/lib/esm/check/precondition/PreconditionFailure.js' {
  declare module.exports: $Exports<'fast-check/lib/esm/check/precondition/PreconditionFailure'>;
}
declare module 'fast-check/lib/esm/check/property/AsyncProperty.generated.js' {
  declare module.exports: $Exports<'fast-check/lib/esm/check/property/AsyncProperty.generated'>;
}
declare module 'fast-check/lib/esm/check/property/AsyncProperty.generic.js' {
  declare module.exports: $Exports<'fast-check/lib/esm/check/property/AsyncProperty.generic'>;
}
declare module 'fast-check/lib/esm/check/property/AsyncProperty.js' {
  declare module.exports: $Exports<'fast-check/lib/esm/check/property/AsyncProperty'>;
}
declare module 'fast-check/lib/esm/check/property/IRawProperty.js' {
  declare module.exports: $Exports<'fast-check/lib/esm/check/property/IRawProperty'>;
}
declare module 'fast-check/lib/esm/check/property/Property.generated.js' {
  declare module.exports: $Exports<'fast-check/lib/esm/check/property/Property.generated'>;
}
declare module 'fast-check/lib/esm/check/property/Property.generic.js' {
  declare module.exports: $Exports<'fast-check/lib/esm/check/property/Property.generic'>;
}
declare module 'fast-check/lib/esm/check/property/Property.js' {
  declare module.exports: $Exports<'fast-check/lib/esm/check/property/Property'>;
}
declare module 'fast-check/lib/esm/check/property/SkipAfterProperty.js' {
  declare module.exports: $Exports<'fast-check/lib/esm/check/property/SkipAfterProperty'>;
}
declare module 'fast-check/lib/esm/check/property/TimeoutProperty.js' {
  declare module.exports: $Exports<'fast-check/lib/esm/check/property/TimeoutProperty'>;
}
declare module 'fast-check/lib/esm/check/property/UnbiasedProperty.js' {
  declare module.exports: $Exports<'fast-check/lib/esm/check/property/UnbiasedProperty'>;
}
declare module 'fast-check/lib/esm/check/runner/configuration/GlobalParameters.js' {
  declare module.exports: $Exports<'fast-check/lib/esm/check/runner/configuration/GlobalParameters'>;
}
declare module 'fast-check/lib/esm/check/runner/configuration/Parameters.js' {
  declare module.exports: $Exports<'fast-check/lib/esm/check/runner/configuration/Parameters'>;
}
declare module 'fast-check/lib/esm/check/runner/configuration/QualifiedParameters.js' {
  declare module.exports: $Exports<'fast-check/lib/esm/check/runner/configuration/QualifiedParameters'>;
}
declare module 'fast-check/lib/esm/check/runner/configuration/RandomType.js' {
  declare module.exports: $Exports<'fast-check/lib/esm/check/runner/configuration/RandomType'>;
}
declare module 'fast-check/lib/esm/check/runner/configuration/VerbosityLevel.js' {
  declare module.exports: $Exports<'fast-check/lib/esm/check/runner/configuration/VerbosityLevel'>;
}
declare module 'fast-check/lib/esm/check/runner/DecorateProperty.js' {
  declare module.exports: $Exports<'fast-check/lib/esm/check/runner/DecorateProperty'>;
}
declare module 'fast-check/lib/esm/check/runner/reporter/ExecutionStatus.js' {
  declare module.exports: $Exports<'fast-check/lib/esm/check/runner/reporter/ExecutionStatus'>;
}
declare module 'fast-check/lib/esm/check/runner/reporter/ExecutionTree.js' {
  declare module.exports: $Exports<'fast-check/lib/esm/check/runner/reporter/ExecutionTree'>;
}
declare module 'fast-check/lib/esm/check/runner/reporter/RunDetails.js' {
  declare module.exports: $Exports<'fast-check/lib/esm/check/runner/reporter/RunDetails'>;
}
declare module 'fast-check/lib/esm/check/runner/reporter/RunExecution.js' {
  declare module.exports: $Exports<'fast-check/lib/esm/check/runner/reporter/RunExecution'>;
}
declare module 'fast-check/lib/esm/check/runner/Runner.js' {
  declare module.exports: $Exports<'fast-check/lib/esm/check/runner/Runner'>;
}
declare module 'fast-check/lib/esm/check/runner/RunnerIterator.js' {
  declare module.exports: $Exports<'fast-check/lib/esm/check/runner/RunnerIterator'>;
}
declare module 'fast-check/lib/esm/check/runner/Sampler.js' {
  declare module.exports: $Exports<'fast-check/lib/esm/check/runner/Sampler'>;
}
declare module 'fast-check/lib/esm/check/runner/SourceValuesIterator.js' {
  declare module.exports: $Exports<'fast-check/lib/esm/check/runner/SourceValuesIterator'>;
}
declare module 'fast-check/lib/esm/check/runner/Tosser.js' {
  declare module.exports: $Exports<'fast-check/lib/esm/check/runner/Tosser'>;
}
declare module 'fast-check/lib/esm/check/runner/utils/PathWalker.js' {
  declare module.exports: $Exports<'fast-check/lib/esm/check/runner/utils/PathWalker'>;
}
declare module 'fast-check/lib/esm/check/runner/utils/RunDetailsFormatter.js' {
  declare module.exports: $Exports<'fast-check/lib/esm/check/runner/utils/RunDetailsFormatter'>;
}
declare module 'fast-check/lib/esm/check/symbols.js' {
  declare module.exports: $Exports<'fast-check/lib/esm/check/symbols'>;
}
declare module 'fast-check/lib/esm/fast-check-default.js' {
  declare module.exports: $Exports<'fast-check/lib/esm/fast-check-default'>;
}
declare module 'fast-check/lib/esm/fast-check.js' {
  declare module.exports: $Exports<'fast-check/lib/esm/fast-check'>;
}
declare module 'fast-check/lib/esm/random/generator/Random.js' {
  declare module.exports: $Exports<'fast-check/lib/esm/random/generator/Random'>;
}
declare module 'fast-check/lib/esm/stream/LazyIterableIterator.js' {
  declare module.exports: $Exports<'fast-check/lib/esm/stream/LazyIterableIterator'>;
}
declare module 'fast-check/lib/esm/stream/Stream.js' {
  declare module.exports: $Exports<'fast-check/lib/esm/stream/Stream'>;
}
declare module 'fast-check/lib/esm/stream/StreamHelpers.js' {
  declare module.exports: $Exports<'fast-check/lib/esm/stream/StreamHelpers'>;
}
declare module 'fast-check/lib/esm/utils/globalThis.js' {
  declare module.exports: $Exports<'fast-check/lib/esm/utils/globalThis'>;
}
declare module 'fast-check/lib/esm/utils/hash.js' {
  declare module.exports: $Exports<'fast-check/lib/esm/utils/hash'>;
}
declare module 'fast-check/lib/esm/utils/stringify.js' {
  declare module.exports: $Exports<'fast-check/lib/esm/utils/stringify'>;
}
declare module 'fast-check/lib/fast-check-default.js' {
  declare module.exports: $Exports<'fast-check/lib/fast-check-default'>;
}
declare module 'fast-check/lib/fast-check.js' {
  declare module.exports: $Exports<'fast-check/lib/fast-check'>;
}
declare module 'fast-check/lib/random/generator/Random.js' {
  declare module.exports: $Exports<'fast-check/lib/random/generator/Random'>;
}
declare module 'fast-check/lib/stream/LazyIterableIterator.js' {
  declare module.exports: $Exports<'fast-check/lib/stream/LazyIterableIterator'>;
}
declare module 'fast-check/lib/stream/Stream.js' {
  declare module.exports: $Exports<'fast-check/lib/stream/Stream'>;
}
declare module 'fast-check/lib/stream/StreamHelpers.js' {
  declare module.exports: $Exports<'fast-check/lib/stream/StreamHelpers'>;
}
declare module 'fast-check/lib/utils/globalThis.js' {
  declare module.exports: $Exports<'fast-check/lib/utils/globalThis'>;
}
declare module 'fast-check/lib/utils/hash.js' {
  declare module.exports: $Exports<'fast-check/lib/utils/hash'>;
}
declare module 'fast-check/lib/utils/stringify.js' {
  declare module.exports: $Exports<'fast-check/lib/utils/stringify'>;
}
