// flow-typed signature: 6dc72adb83dccfc0ffc297a5e4e45358
// flow-typed version: <<STUB>>/fast-check_v2.7.0/flow_v0.138.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fast-check'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fast-check' {
  declare module.exports: any;
}
